FROM node:latest

# Create app directory
COPY ./app /app/
WORKDIR /app

# Run production app dependencies
# Install app dependencies
RUN npm install . && \
chmod a+x /app/node_modules/.bin/react-scripts &&\
npm run build && \
npm install -g serve
# Run prod
CMD [ "serve", "-s", "build" ]
