version: '2'
services:

  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d

  frontend:
    build: ./frontend
    env_file: ./frontend/config.env
    expose:
            - "80"
    volumes:
            - ./frontend/app:/app
    depends_on:
      - "backend"

  backend:
    build: ./backend
    expose:
            - "8080"
    volumes:
            - ./backend/app:/app
    environment:
            DEBUG: $DEBUG
  nginx:
    build: ./nginx
    links:
        - frontend:frontend
        - backend:backend
    ports:
        - "80:80"
    depends_on:
      - "frontend"

